#!/usr/bin/env node
// Generated by CoffeeScript 1.10.0
(function() {
  var client, filename, fs, html, message, opn, temp;

  fs = require('fs');

  opn = require('opn');

  temp = require('temp');

  client = function() {
    var ctx, osc;
    ctx = new (AudioContext || webkitAudioContext)();
    osc = ctx.createOscillator();
    osc.frequency.value = 2000;
    osc.start();
    osc.connect(ctx.destination);
    return window.onbeforeunload = function() {
      return "Did you " + document.body.firstChild.textContent + "?";
    };
  };

  message = process.argv.slice(2).join(' ') || "Do things!";

  html = "<h1>" + message + "</h1><script>(" + (client.toString()) + ")()</script>";

  filename = temp.path({
    suffix: '.html'
  });

  fs.writeFileSync(filename, html, 'utf8');

  opn(filename, {
    wait: false
  });

  setTimeout((function() {}), 500);

  process.on('exit', function() {
    return fs.unlinkSync(filename);
  });

}).call(this);
